import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import RQProvider from "./RQProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RQProvider>
      <html lang="en">
        <body
          className={`${inter.className} dark mx-auto max-w-6xl text-2xl p-5`}
        >
          {children}
        </body>
      </html>
    </RQProvider>
  );
}
